In [42]:
import pandas as pd
import numpy as np
import warnings

# Ignore all warnings
warnings.filterwarnings("ignore")

In [2]:
# create dataframe
df = pd.DataFrame([[8,8,4],[7,9,5,],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [13]:
# architecture_input into layer_dims -> [2 2 1]
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):

    # intial point of w is 0.1 and b is 0
    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l])) * 0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

  return parameters

In [16]:
# code explanation
layer_dims = [2,2,1]
# first loop -> l=1
np.ones((layer_dims[1-1],layer_dims[1])) #-> layer_dims[1-1] create 2D row and layer_dims[1] 2D column -> 2x2

array([[1., 1.],
       [1., 1.]])

In [12]:
layer_dims[1-1] # -> 2 row (layer_dim[0] == 2) same for layer_dims[1] == 2

2

In [14]:
# check architecture
parameters = initialize_parameters(layer_dims)
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

W1 - ([[w11,w12],<br>
      [w21,w22]]),<br>
b1 - [[B1],[B2]]

In [18]:
# calculate output of given neuron
def linear_forward(A_prev, W, b):
  Z = np.dot(W.T, A_prev) + b

  return Z

In [19]:
# forward propagation
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2   #number of layer in the neural network

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    print("A"+str(l-1)+": ", A_prev)
    print("W"+str(l)+": ", Wl)
    print("b"+str(l)+": ", bl)
    print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    print("A"+str(l)+": ", A)
    print("**"*20)

  return A,A_prev # return A_prev because we use previous value many times

In [20]:
# testing upper function
X = df[['cgpa','profile_score']].values[0].reshape(2,1) # input layer with 2 function
y = df[['lpa']].values[0][0]

# parameters intialization
parameters = initialize_parameters([2,2,1])

L_layer_forward(X, parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [22]:
# loss for first student
(y-0.32)**2

13.5424

In [27]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1) # input layer with 2 function
y = df[['lpa']].values[0][0]

# parameters intialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [31]:
y_hat = y_hat[0][0]

In [32]:
y_hat

0.32000000000000006

In [23]:
# update 9 parameters
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [33]:
update_parameters(parameters,y,y_hat,A1,X)

In [36]:
# weights and bias changed
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

# **second student**

In [37]:
X = df[['cgpa','profile_score']].values[1].reshape(2,1) # input layer with 2 function
y = df[['lpa']].values[1][0]

# parameters intialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

A0:  [[7]
 [9]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [38]:
update_parameters(parameters,y,y_hat,A1,X)

<ipython-input-23-d9829bfb84a0>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-23-d9829bfb84a0>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-23-d9829bfb84a0>:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

In [39]:
parameters

{'W1': array([[0.10753323, 0.10968558],
        [0.10753323, 0.10968558]]),
 'b1': array([[0.00107618],
        [0.00107618]]),
 'W2': array([[0.114976],
        [0.114976]]),
 'b2': array([[0.124336]])}

# **For third student**

In [41]:
X = df[['cgpa','profile_score']].values[2].reshape(2,1) # input layer with 2 function
y = df[['lpa']].values[2][0]

# parameters intialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0:  [[ 6]
 [10]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************
----------------------------------------


<ipython-input-23-d9829bfb84a0>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
<ipython-input-23-d9829bfb84a0>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
<ipython-input-23-d9829bfb84a0>:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

{'W1': array([[0.10805488, 0.11342479],
        [0.10805488, 0.11342479]]),
 'b1': array([[0.00134248],
        [0.00134248]]),
 'W2': array([[0.118176],
        [0.118176]]),
 'b2': array([[0.129536]])}

In [45]:
X = df[['cgpa','profile_score']].values[3].reshape(2,1) # input layer with 2 function
y = df[['lpa']].values[3][0]

# parameters intialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

update_parameters(parameters,y,y_hat,A1,X)

parameters

A0:  [[ 5]
 [12]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.7]
 [1.7]]
****************************************
A1:  [[1.7]
 [1.7]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.34]]
****************************************


{'W1': array([[0.10816809, 0.11960342],
        [0.10816809, 0.11960342]]),
 'b1': array([[0.00163362],
        [0.00163362]]),
 'W2': array([[0.122644],
        [0.122644]]),
 'b2': array([[0.135964]])}

In [46]:
# epochs implementation
parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
A2:  [[0.50054357]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1:  [[0.0019667]
 [0.0019667]]
----------------------------------------
A1:  [[1.83539945]
 [1.87200826]]
****************************************
A1:  [[1.83539945]
 [1.87200826]]
W2:  [[0.12712927]
 [0.127

{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

# **Using Tensorflow**

In [1]:
import numpy as np
import pandas as pd

import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [4]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [5]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [7]:
model = Sequential()

model.add(Dense(2,activation = 'linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.get_weights()

[array([[ 0.30078363,  0.48811603],
        [-1.0272295 , -0.56647414]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.0894505],
        [-1.1072729]], dtype=float32),
 array([0.], dtype=float32)]

In [10]:
new_weights = [np.array([[ 0.1,  0.1],
        [0.1 , 0.1]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1],
        [0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [11]:
model.set_weights(new_weights)

In [12]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [15]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [16]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 33.6870
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.3853  
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30.4421 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22.6802 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20.7411 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29.4856 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29.7474 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.2332 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 24.6592 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21.9353 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.2657 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 23.4334 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29.1791 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.0040 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.1839 
Epoch 16/75
4/4 ━━━

In [17]:
model.get_weights()

[array([[0.37342697, 0.37342697],
        [0.36524266, 0.36524266]], dtype=float32),
 array([0.272029, 0.272029], dtype=float32),
 array([[0.37261742],
        [0.37261742]], dtype=float32),
 array([0.20447752], dtype=float32)]